import re

from markdownify import markdownify


class TemplateRenderer:

    # Unicode superscript translation table
    SUPERSCRIPT_MAP = str.maketrans({
        "0": "⁰",
        "1": "¹",
        "2": "²",
        "3": "³",
        "4": "⁴",
        "5": "⁵",
        "6": "⁶",
        "7": "⁷",
        "8": "⁸",
        "9": "⁹",
        "+": "⁺",
        "-": "⁻",
    })

    @staticmethod
    def clean_markdown(markdown: str) -> str:
        """
        Normalize markdown generated by markdownify.
        """

        # Normalize line endings
        markdown = markdown.replace("\r\n", "\n")

        # ---------------------------------------
        # Normalize headings
        # ---------------------------------------

        markdown = re.sub(
            r"\*\*Example\s+(\d+):\*\*",
            r"## Example \1",
            markdown
        )

        markdown = markdown.replace(
            "**Constraints:**",
            "## Constraints"
        )

        markdown = re.sub(
            r"Follow[- ]up\s*:?\s*",
            "## Follow-up\n\n",
            markdown,
            flags=re.IGNORECASE
        )

        # ---------------------------------------
        # Remove remaining bold markers
        # ---------------------------------------

        markdown = markdown.replace("**", "")

        # Remove trailing spaces
        markdown = re.sub(
            r"[ \t]+$",
            "",
            markdown,
            flags=re.MULTILINE
        )

        # Collapse excessive blank lines
        markdown = re.sub(
            r"\n{3,}",
            "\n\n",
            markdown
        )

        return markdown.strip()

    @staticmethod
    def to_markdown(html):
        """
        Convert LeetCode HTML into clean Markdown.
        """

        # Convert HTML <sup> tags into Unicode superscripts
        html = re.sub(
            r"<sup>(.*?)</sup>",
            lambda m: m.group(1).translate(
                TemplateRenderer.SUPERSCRIPT_MAP
            ),
            html,
            flags=re.IGNORECASE
        )

        markdown = markdownify(
            html,
            heading_style="ATX",
            bullets="-"
        )

        return TemplateRenderer.clean_markdown(markdown)

    @staticmethod
    def problem_statement(markdown):
        """
        Extract everything before the first example.
        """

        match = re.search(
            r"^## Example\s+1",
            markdown,
            re.MULTILINE
        )

        if match:
            return markdown[:match.start()].strip()

        return markdown.strip()

    @staticmethod
    def examples(markdown):
        """
        Extract all examples.
        """

        start = re.search(
            r"^## Example\s+1",
            markdown,
            re.MULTILINE
        )

        if not start:
            return ""

        end = re.search(
            r"^## Constraints",
            markdown,
            re.MULTILINE
        )

        if end:
            return markdown[start.start():end.start()].strip()

        return markdown[start.start():].strip()

    @staticmethod
    def constraints(markdown):
        """
        Extract constraints section.
        """

        start = re.search(
            r"^## Constraints",
            markdown,
            re.MULTILINE
        )

        if not start:
            return ""

        end = re.search(
            r"^## Follow-up",
            markdown,
            re.MULTILINE
        )

        if end:
            section = markdown[start.start():end.start()]
        else:
            section = markdown[start.start():]

        section = re.sub(
            r"^## Constraints\s*",
            "",
            section,
            flags=re.MULTILINE
        )

        return section.strip()

    @staticmethod
    def follow_up(markdown):
        """
        Extract follow-up section (if present).
        """

        start = re.search(
            r"^## Follow-up",
            markdown,
            re.MULTILINE
        )

        if not start:
            return ""

        section = markdown[start.start():]

        section = re.sub(
            r"^## Follow-up\s*",
            "",
            section,
            flags=re.MULTILINE
        )

        return section.strip()